sudo: false
language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run coverage.report
  - npm run semantic-release
